// Departementen zoals ze op Franse kentekens (SIV, sinds 2009) kunnen staan.
// Velden: code, naam, prefectuur, regio, toelichting.
// De toelichtingen zijn bewust kort: één weetje per departement.
(function (root) {
  const D = (code, naam, prefectuur, regio, toelichting) => ({ code, naam, prefectuur, regio, toelichting });

  const DEPARTEMENTEN = [
    D('01', 'Ain', 'Bourg-en-Bresse', 'Auvergne-Rhône-Alpes', 'Genoemd naar de rivier de Ain. Bekend om de Bresse-kip, de enige kip met een AOC-keurmerk.'),
    D('02', 'Aisne', 'Laon', 'Hauts-de-France', 'Genoemd naar de rivier de Aisne. Laon ligt spectaculair op een heuvel met een grote gotische kathedraal.'),
    D('03', 'Allier', 'Moulins', 'Auvergne-Rhône-Alpes', 'Genoemd naar de rivier de Allier. Hier ligt Vichy, bekend van het bronwater en de oorlogsregering.'),
    D('04', 'Alpes-de-Haute-Provence', 'Digne-les-Bains', 'Provence-Alpes-Côte d\'Azur', 'Lavendelvelden op het plateau van Valensole en de Gorges du Verdon (met de Var).'),
    D('05', 'Hautes-Alpes', 'Gap', 'Provence-Alpes-Côte d\'Azur', 'Hooggelegen Alpendepartement; Briançon is een van de hoogste steden van Europa.'),
    D('06', 'Alpes-Maritimes', 'Nice', 'Provence-Alpes-Côte d\'Azur', 'De Côte d\'Azur: Nice, Cannes en Antibes. Grenst aan Monaco en Italië.'),
    D('07', 'Ardèche', 'Privas', 'Auvergne-Rhône-Alpes', 'Genoemd naar de rivier de Ardèche. Kano\'s, de Pont d\'Arc en de grot van Chauvet.'),
    D('08', 'Ardennes', 'Charleville-Mézières', 'Grand Est', 'Genoemd naar het Ardennenwoud. Charleville is de geboorteplaats van de dichter Rimbaud.'),
    D('09', 'Ariège', 'Foix', 'Occitanie', 'Genoemd naar de rivier de Ariège. Pyreneeëndepartement aan de grens met Andorra.'),
    D('10', 'Aube', 'Troyes', 'Grand Est', 'Genoemd naar de rivier de Aube. Troyes heeft een middeleeuws centrum met vakwerkhuizen; ook champagnegebied.'),
    D('11', 'Aude', 'Carcassonne', 'Occitanie', 'Genoemd naar de rivier de Aude. De vestingstad Carcassonne en veel katharenkastelen.'),
    D('12', 'Aveyron', 'Rodez', 'Occitanie', 'Genoemd naar de rivier de Aveyron. Het viaduct van Millau en de roquefortkaas.'),
    D('13', 'Bouches-du-Rhône', 'Marseille', 'Provence-Alpes-Côte d\'Azur', '"Monden van de Rhône". Marseille, de Camargue en Aix-en-Provence.'),
    D('14', 'Calvados', 'Caen', 'Normandie', 'Genoemd naar een rotsrif voor de kust. De landingsstranden van D-Day en de appelbrandewijn.'),
    D('15', 'Cantal', 'Aurillac', 'Auvergne-Rhône-Alpes', 'Genoemd naar het vulkanische Cantalmassief. Ook de naam van een bekende kaas.'),
    D('16', 'Charente', 'Angoulême', 'Nouvelle-Aquitaine', 'Genoemd naar de rivier de Charente. Cognac ligt hier; Angoulême heeft een groot stripfestival.'),
    D('17', 'Charente-Maritime', 'La Rochelle', 'Nouvelle-Aquitaine', 'Kustdepartement met La Rochelle en de eilanden Ré en Oléron.'),
    D('18', 'Cher', 'Bourges', 'Centre-Val de Loire', 'Genoemd naar de rivier de Cher. Bourges heeft een grote gotische kathedraal (werelderfgoed).'),
    D('19', 'Corrèze', 'Tulle', 'Nouvelle-Aquitaine', 'Genoemd naar de rivier de Corrèze. Groen, heuvelachtig binnenland.'),
    D('2A', 'Corse-du-Sud', 'Ajaccio', 'Corse', 'Zuid-Corsica. Ajaccio is de geboortestad van Napoleon. Sinds 1976 is Corsica gesplitst; daarom bestaat 20 niet meer.'),
    D('2B', 'Haute-Corse', 'Bastia', 'Corse', 'Noord-Corsica met Bastia, Calvi en het schiereiland Cap Corse.'),
    D('21', 'Côte-d\'Or', 'Dijon', 'Bourgogne-Franche-Comté', '"Gouden helling": de Bourgogne-wijnen. Dijon is bekend van de mosterd.'),
    D('22', 'Côtes-d\'Armor', 'Saint-Brieuc', 'Bretagne', 'Bretonse noordkust met de roze granietkust (Côte de Granit Rose).'),
    D('23', 'Creuse', 'Guéret', 'Nouvelle-Aquitaine', 'Genoemd naar de rivier de Creuse. Een van de dunst bevolkte departementen; Aubusson is bekend van wandtapijten.'),
    D('24', 'Dordogne', 'Périgueux', 'Nouvelle-Aquitaine', 'Genoemd naar de rivier de Dordogne. Het Périgord, de grot van Lascaux en veel kastelen.'),
    D('25', 'Doubs', 'Besançon', 'Bourgogne-Franche-Comté', 'Genoemd naar de rivier de Doubs. Comtékaas en de Jura aan de Zwitserse grens.'),
    D('26', 'Drôme', 'Valence', 'Auvergne-Rhône-Alpes', 'Genoemd naar de rivier de Drôme. Nougat uit Montélimar.'),
    D('27', 'Eure', 'Évreux', 'Normandie', 'Genoemd naar de rivier de Eure. Giverny, de tuin van Monet.'),
    D('28', 'Eure-et-Loir', 'Chartres', 'Centre-Val de Loire', 'Genoemd naar de rivieren Eure en Loir. De kathedraal van Chartres en de graanvlakte van de Beauce.'),
    D('29', 'Finistère', 'Quimper', 'Bretagne', '"Einde van de aarde": de westpunt van Frankrijk, met Brest.'),
    D('30', 'Gard', 'Nîmes', 'Occitanie', 'Genoemd naar de rivier de Gard. De Romeinse Pont du Gard en de arena van Nîmes.'),
    D('31', 'Haute-Garonne', 'Toulouse', 'Occitanie', 'Toulouse, "la ville rose", thuisbasis van Airbus.'),
    D('32', 'Gers', 'Auch', 'Occitanie', 'Genoemd naar de rivier de Gers. Armagnac, eendenlever en het land van d\'Artagnan.'),
    D('33', 'Gironde', 'Bordeaux', 'Nouvelle-Aquitaine', 'Genoemd naar de riviermonding de Gironde. Bordeaux, de wijn en de Dune du Pilat.'),
    D('34', 'Hérault', 'Montpellier', 'Occitanie', 'Genoemd naar de rivier de Hérault. Montpellier, Sète en veel Languedoc-wijn.'),
    D('35', 'Ille-et-Vilaine', 'Rennes', 'Bretagne', 'Genoemd naar de rivieren Ille en Vilaine. Rennes en de vestingstad Saint-Malo.'),
    D('36', 'Indre', 'Châteauroux', 'Centre-Val de Loire', 'Genoemd naar de rivier de Indre. Het landelijke Berry, de streek van George Sand.'),
    D('37', 'Indre-et-Loire', 'Tours', 'Centre-Val de Loire', 'Loirekastelen als Chenonceau en Amboise.'),
    D('38', 'Isère', 'Grenoble', 'Auvergne-Rhône-Alpes', 'Genoemd naar de rivier de Isère. Grenoble, hoofdstad van de Alpen.'),
    D('39', 'Jura', 'Lons-le-Saunier', 'Bourgogne-Franche-Comté', 'Genoemd naar het Juragebergte. Gele wijn (vin jaune) en comtékaas.'),
    D('40', 'Landes', 'Mont-de-Marsan', 'Nouvelle-Aquitaine', '"Heidevelden": nu het grootste aangeplante dennenbos van West-Europa, plus surfstranden.'),
    D('41', 'Loir-et-Cher', 'Blois', 'Centre-Val de Loire', 'Genoemd naar de rivieren Loir en Cher. Het kasteel van Chambord.'),
    D('42', 'Loire', 'Saint-Étienne', 'Auvergne-Rhône-Alpes', 'Genoemd naar de Loire. Saint-Étienne, oude mijn- en industriestad.'),
    D('43', 'Haute-Loire', 'Le Puy-en-Velay', 'Auvergne-Rhône-Alpes', 'Vulkaanlandschap; Le Puy is een startpunt van de pelgrimsroute naar Santiago. Groene linzen.'),
    D('44', 'Loire-Atlantique', 'Nantes', 'Pays de la Loire', 'Waar de Loire in de Atlantische Oceaan uitmondt. Nantes, en de stranden van La Baule.'),
    D('45', 'Loiret', 'Orléans', 'Centre-Val de Loire', 'Genoemd naar het riviertje de Loiret. Orléans, de stad van Jeanne d\'Arc.'),
    D('46', 'Lot', 'Cahors', 'Occitanie', 'Genoemd naar de rivier de Lot. Rocamadour, Saint-Cirq-Lapopie en de zwarte wijn van Cahors.'),
    D('47', 'Lot-et-Garonne', 'Agen', 'Nouvelle-Aquitaine', 'Genoemd naar de rivieren Lot en Garonne. Agen is bekend om de gedroogde pruimen.'),
    D('48', 'Lozère', 'Mende', 'Occitanie', 'Het dunst bevolkte departement van Frankrijk. De Cevennen en de Gorges du Tarn.'),
    D('49', 'Maine-et-Loire', 'Angers', 'Pays de la Loire', 'Genoemd naar de rivieren Maine en Loire. Angers, Saumur en veel Loirewijn.'),
    D('50', 'Manche', 'Saint-Lô', 'Normandie', 'Genoemd naar het Kanaal (La Manche). De Mont-Saint-Michel en Cherbourg.'),
    D('51', 'Marne', 'Châlons-en-Champagne', 'Grand Est', 'Genoemd naar de rivier de Marne. Reims en Épernay: het hart van de champagne.'),
    D('52', 'Haute-Marne', 'Chaumont', 'Grand Est', 'Bovenloop van de Marne. Colombey-les-Deux-Églises, het dorp van De Gaulle.'),
    D('53', 'Mayenne', 'Laval', 'Pays de la Loire', 'Genoemd naar de rivier de Mayenne. Landelijk en groen.'),
    D('54', 'Meurthe-et-Moselle', 'Nancy', 'Grand Est', 'Genoemd naar de rivieren Meurthe en Moezel. Het Place Stanislas in Nancy.'),
    D('55', 'Meuse', 'Bar-le-Duc', 'Grand Est', 'Genoemd naar de Maas. Het slagveld van Verdun (1916).'),
    D('56', 'Morbihan', 'Vannes', 'Bretagne', '"Kleine zee" in het Bretons. De menhirs van Carnac en de Golfe du Morbihan.'),
    D('57', 'Moselle', 'Metz', 'Grand Est', 'Genoemd naar de Moezel. Metz met het Centre Pompidou-Metz.'),
    D('58', 'Nièvre', 'Nevers', 'Bourgogne-Franche-Comté', 'Genoemd naar het riviertje de Nièvre. De Morvan en de wijn van Pouilly.'),
    D('59', 'Nord', 'Lille', 'Hauts-de-France', 'Het meest bevolkte departement. Lille, Duinkerken en de grens met België.'),
    D('60', 'Oise', 'Beauvais', 'Hauts-de-France', 'Genoemd naar de rivier de Oise. Het kasteel van Chantilly en de luchthaven Beauvais.'),
    D('61', 'Orne', 'Alençon', 'Normandie', 'Genoemd naar de rivier de Orne. De camembert komt uit dit departement.'),
    D('62', 'Pas-de-Calais', 'Arras', 'Hauts-de-France', 'Genoemd naar de Straat van Calais. Calais, de Opaalkust en de Kanaaltunnel.'),
    D('63', 'Puy-de-Dôme', 'Clermont-Ferrand', 'Auvergne-Rhône-Alpes', 'Genoemd naar de vulkaan Puy de Dôme. Clermont-Ferrand, thuisbasis van Michelin.'),
    D('64', 'Pyrénées-Atlantiques', 'Pau', 'Nouvelle-Aquitaine', 'Baskenland en Béarn: Biarritz, Bayonne en de westelijke Pyreneeën.'),
    D('65', 'Hautes-Pyrénées', 'Tarbes', 'Occitanie', 'Lourdes, de Pic du Midi en de Col du Tourmalet.'),
    D('66', 'Pyrénées-Orientales', 'Perpignan', 'Occitanie', 'Frans Catalonië: Perpignan, Collioure en de Canigou.'),
    D('67', 'Bas-Rhin', 'Strasbourg', 'Grand Est', 'Neder-Rijn: Straatsburg, zetel van het Europees Parlement.'),
    D('68', 'Haut-Rhin', 'Colmar', 'Grand Est', 'Opper-Rijn: Colmar, Mulhouse en de Elzasser wijnroute.'),
    D('69', 'Rhône', 'Lyon', 'Auvergne-Rhône-Alpes', 'Genoemd naar de Rhône. Lyon (sinds 2015 een aparte metropool, maar kentekens houden 69) en de Beaujolais.'),
    D('70', 'Haute-Saône', 'Vesoul', 'Bourgogne-Franche-Comté', 'Bovenloop van de Saône. De kapel van Le Corbusier in Ronchamp.'),
    D('71', 'Saône-et-Loire', 'Mâcon', 'Bourgogne-Franche-Comté', 'Genoemd naar de Saône en de Loire. De abdij van Cluny.'),
    D('72', 'Sarthe', 'Le Mans', 'Pays de la Loire', 'Genoemd naar de rivier de Sarthe. De 24 uur van Le Mans.'),
    D('73', 'Savoie', 'Chambéry', 'Auvergne-Rhône-Alpes', 'Wintersport: Val d\'Isère, Courchevel, Les Arcs. Pas sinds 1860 Frans.'),
    D('74', 'Haute-Savoie', 'Annecy', 'Auvergne-Rhône-Alpes', 'De Mont Blanc, Chamonix en het meer van Annecy.'),
    D('75', 'Paris', 'Paris', 'Île-de-France', 'Stad en departement tegelijk. Veel leaseauto\'s staan op 75 omdat de eigenaar vrij mag kiezen.'),
    D('76', 'Seine-Maritime', 'Rouen', 'Normandie', 'Seinemonding: Rouen, Le Havre en de krijtrotsen van Étretat.'),
    D('77', 'Seine-et-Marne', 'Melun', 'Île-de-France', 'Grootste departement van Île-de-France. Disneyland Paris en Fontainebleau.'),
    D('78', 'Yvelines', 'Versailles', 'Île-de-France', 'Genoemd naar het bos van Yveline. Het paleis van Versailles.'),
    D('79', 'Deux-Sèvres', 'Niort', 'Nouvelle-Aquitaine', 'Genoemd naar de twee rivieren Sèvre. Het "groene Venetië" van de Marais poitevin.'),
    D('80', 'Somme', 'Amiens', 'Hauts-de-France', 'Genoemd naar de rivier de Somme. Slagvelden van 1916 en de kathedraal van Amiens.'),
    D('81', 'Tarn', 'Albi', 'Occitanie', 'Genoemd naar de rivier de Tarn. Albi, de rode bisschopsstad, en Toulouse-Lautrec.'),
    D('82', 'Tarn-et-Garonne', 'Montauban', 'Occitanie', 'Het jongste departement van het vasteland (1808). Moissac en zijn kloostergang.'),
    D('83', 'Var', 'Toulon', 'Provence-Alpes-Côte d\'Azur', 'Genoemd naar de rivier de Var, die er door een grenswijziging niet meer doorheen stroomt. Saint-Tropez.'),
    D('84', 'Vaucluse', 'Avignon', 'Provence-Alpes-Côte d\'Azur', 'Genoemd naar de bron Fontaine-de-Vaucluse. Avignon, de Mont Ventoux.'),
    D('85', 'Vendée', 'La Roche-sur-Yon', 'Pays de la Loire', 'Genoemd naar het riviertje de Vendée. Stranden en het Puy du Fou.'),
    D('86', 'Vienne', 'Poitiers', 'Nouvelle-Aquitaine', 'Genoemd naar de rivier de Vienne. Poitiers en het pretpark Futuroscope.'),
    D('87', 'Haute-Vienne', 'Limoges', 'Nouvelle-Aquitaine', 'Limoges, de stad van het porselein. Oradour-sur-Glane.'),
    D('88', 'Vosges', 'Épinal', 'Grand Est', 'Genoemd naar de Vogezen. Bossen, meren en de bron van Vittel.'),
    D('89', 'Yonne', 'Auxerre', 'Bourgogne-Franche-Comté', 'Genoemd naar de rivier de Yonne. De wijn van Chablis en de basiliek van Vézelay.'),
    D('90', 'Territoire de Belfort', 'Belfort', 'Bourgogne-Franche-Comté', 'Het stukje Elzas dat na 1871 Frans bleef. De Leeuw van Belfort.'),
    D('91', 'Essonne', 'Évry-Courcouronnes', 'Île-de-France', 'Genoemd naar de rivier de Essonne. Zuidelijke voorsteden van Parijs.'),
    D('92', 'Hauts-de-Seine', 'Nanterre', 'Île-de-France', 'Westelijke voorsteden: het zakendistrict La Défense.'),
    D('93', 'Seine-Saint-Denis', 'Bobigny', 'Île-de-France', 'Noordelijke voorsteden: het Stade de France en de basiliek van Saint-Denis.'),
    D('94', 'Val-de-Marne', 'Créteil', 'Île-de-France', 'Zuidoostelijke voorsteden; de luchthaven Orly ligt deels in dit departement.'),
    D('95', 'Val-d\'Oise', 'Cergy', 'Île-de-France', 'Noordwestelijke voorsteden; een groot deel van de luchthaven Roissy-Charles de Gaulle.'),
    D('971', 'Guadeloupe', 'Basse-Terre', 'Guadeloupe', 'Vlindervormige eilandengroep in de Caraïben.'),
    D('972', 'Martinique', 'Fort-de-France', 'Martinique', 'Caraïbisch eiland met de vulkaan Montagne Pelée.'),
    D('973', 'Guyane', 'Cayenne', 'Guyane', 'In Zuid-Amerika, buurland van Suriname. Lanceerbasis van de Ariane-raketten in Kourou.'),
    D('974', 'La Réunion', 'Saint-Denis', 'La Réunion', 'Vulkaaneiland in de Indische Oceaan (Piton de la Fournaise).'),
    D('976', 'Mayotte', 'Mamoudzou', 'Mayotte', 'Sinds 2011 het jongste departement. Ligt tussen Madagaskar en Mozambique.')
  ];

  // Zeldzaamheden die niet meetellen voor de 101 officiële departementen.
  // Soort 'code': een nummer dat je kunt intoetsen. Soort 'plaat': een bijzonder kentekentype.
  const BONUS = [
    { code: '20', soort: 'code', naam: 'Oud Corsica (20)', toelichting: 'Corsica had nummer 20 tot de splitsing in 2A en 2B in 1976. Alleen nog te zien op heel oude kentekens (oldtimers).' },
    { code: '975', soort: 'code', naam: 'Saint-Pierre-et-Miquelon', toelichting: 'Overzees gebied bij Canada met een eigen kentekensysteem: de plaat begint met SPM (bv. SPM 123 A). Het nummer 975 staat er niet op. Zeer zeldzaam in Europa.' },
    { code: '977', soort: 'code', naam: 'Saint-Barthélemy', toelichting: 'Caraïbisch eiland met een eigen kentekensysteem: het wapen van het eiland, dan 1 tot 3 cijfers en 1 tot 3 letters. Het nummer 977 staat er niet op. Zeer zeldzaam.' },
    { code: '978', soort: 'code', naam: 'Saint-Martin', toelichting: 'Frans deel van het eiland Sint-Maarten, met een eigen kentekensysteem: vier cijfers, een streepje en drie letters (bv. 1234-ABC). Het nummer 978 staat er niet op. Zeer zeldzaam.' },
    { code: '986', soort: 'code', naam: 'Wallis-et-Futuna', toelichting: 'Eilanden in de Stille Oceaan met een eigen kentekensysteem: 1 tot 5 cijfers en dan WF (bv. 1234 WF). Het nummer 986 staat er niet op.' },
    { code: '987', soort: 'code', naam: 'Polynésie française', toelichting: 'Tahiti en omliggende eilanden, met een eigen kentekensysteem: 1 tot 6 cijfers en dan de letter P (bv. 123456 P). Het nummer 987 staat er niet op.' },
    { code: '988', soort: 'code', naam: 'Nouvelle-Calédonie', toelichting: 'Eigen kentekensysteem: 1 tot 6 cijfers en dan NC (bv. 123456 NC). Het nummer 988 staat er niet op. Een auto hiervan in Frankrijk is een topvondst.' },
    { code: 'TT', soort: 'plaat', naam: 'Rode TT-plaat', toelichting: 'Transit Temporaire: witte tekens op een rode plaat, met een gewoon nummer (bv. AB-123-CD) en rechts de vervaldatum (maand/jaar) in plaats van een departement. Voor auto\'s die tijdelijk in Frankrijk rijden of worden uitgevoerd.' },
    { code: 'CD', soort: 'plaat', naam: 'Groene diplomatenplaat', toelichting: 'Groene plaat met oranje tekens (CD, CMD) of witte tekens (C, K). Het eerste nummer staat voor het land of de organisatie.' },
    { code: 'W', soort: 'plaat', naam: 'W garage', toelichting: 'Handelaarskenteken van een garage of dealer: W-123-AB. Sinds 2026 zwarte tekens op een roze plaat; oudere W-platen kunnen nog wit zijn.' },
    { code: 'WW', soort: 'plaat', naam: 'WW tijdelijk', toelichting: 'Tijdelijk kenteken (WW-123-AB), bijvoorbeeld bij import, in afwachting van de definitieve inschrijving. Sinds 2026 zwart op roze, met rechts de vervaldatum in plaats van een departement.' },
    { code: 'ZWART', soort: 'plaat', naam: 'Zwarte oldtimerplaat', toelichting: 'Witte tekens op een zwarte plaat: toegestaan voor oldtimers met een collectiekenteken.' },
    { code: 'FNI', soort: 'plaat', naam: 'Oud FNI-kenteken', toelichting: 'Kenteken van vóór 2009 in de vorm 1234 AB 56. Het laatste getal was het departement waar de auto stond ingeschreven.' },
    { code: 'MIL', soort: 'plaat', naam: 'Legervoertuig', toelichting: 'Franse vlag op de plaat, alleen cijfers, geen departement.' }
  ];

  const api = { DEPARTEMENTEN, BONUS };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.DEP_DATA = api;
})(this);
